export const SET_VALUE = 'SET_VALUE'

export const SET_RGB_VALUE = 'SET_RGB_VALUE'

export const SET_RGB_DROPDOWN_OPENED = 'SET_RGB_DROPDOWN_OPENED'

export const SET_DROPDOWN_OPENED = 'SET_DROPDOWN_OPENED'
